import type { Food } from "./types";

// 3. ข้อมูลอาหารพร้อม Type
export const foods: Food[] = [
  
  {
    id: 1,
    name: "แอปเปิ้ล",
    image: "/image/fruit/Apple.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    price: 39,
  },
  {
    id: 2,
    name: "อะโวคาโด",
    image: "/image/fruit/Avocado.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    price: 49,
  },
  {
    id: 3,
    name: "กล้วยหอม",
    image: "/image/fruit/Banana.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.4,
    price: 29,
  },
  {
    id: 4,
    name: "บลูเบอร์รี",
    image: "/image/fruit/Blueberry.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    price: 49,
  },
  {
    id: 5,
    name: "ส้ม",
    image: "/image/fruit/Orange.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    price: 39,
  },
  {
    id: 6,
    name: "ฝรั่ง",
    image: "/image/fruit/Guava.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 68,
    protein: 2.6,
    carbs: 14.3,
    fat: 1.0,
    price: 39,
  },
  {
    id: 7,
    name: "มะละกอสุก",
    image: "/image/fruit/Papaya.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 43,
    protein: 0.5,
    carbs: 10.8,
    fat: 0.3,
    price: 29,
  },
  {
    id: 8,
    name: "แก้วมังกร",
    image: "/image/fruit/DragonFruit.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 60,
    protein: 1.2,
    carbs: 13.0,
    fat: 0.5,
    price: 39,
  },
  {
    id: 9,
    name: "แตงโม",
    image: "/image/fruit/Watermelon.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    price: 29,
  },
  {
    id: 10,
    name: "สตรอว์เบอร์รี",
    image: "/image/fruit/Strawberry.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    price: 49,
  },


  {
    id: 11,
    name: "ชาเขียวมะลิ",
    image: "/image/water/JasmineGreenTea.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    price: 39,
  },
  {
    id: 12,
    name: "ชาเขียวร้อน",
    image: "/image/water/GreenTea.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    price: 39,
  },
  {
    id: 13,
    name: "น้ำมะพร้าวสด",
    image: "/image/water/CoconutWater.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 45,
    protein: 0.5,
    carbs: 11,
    fat: 0.2,
    price: 39,
  },
  {
    id: 14,
    name: "น้ำเต้าหู้",
    image: "/image/water/SoyMilk.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 80,
    protein: 7,
    carbs: 4,
    fat: 4,
    price: 29,
  },
  {
    id: 15,
    name: "น้ำขิง",
    image: "/image/water/GingerTea.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 10,
    protein: 0.2,
    carbs: 2,
    fat: 0,
    price: 29,
  },
  {
    id: 16,
    name: "น้ำแครอทขิงแอปเปิลปั่น",
    image: "/image/water/TomatoGingerApp.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 41,
    protein: 1.5,
    carbs: 9,
    fat: 0.3,
    price: 39,
  },
  {
    id: 17,
    name: "น้ำใบบัวบก",
    image: "/image/water/GotuKolaJuice.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 35,
    protein: 0.5,
    carbs: 8,
    fat: 0.1,
    price: 29,
  },
  {
    id: 18,
    name: "นมอัลมอนด์",
    image: "/image/water/AlmondMilk.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 39,
    protein: 1.5,
    carbs: 1.5,
    fat: 3,
    price: 59,
  },
  {
    id: 19,
    name: "น้ำมะเขือเทศแตงกวาปั่น",
    image: "/image/water/TomatoGourdSmoothie.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 50,
    protein: 1.2,
    carbs: 11,
    fat: 0.2,
    price: 39,
  },
  {
    id: 20,
    name: "ลาสซี่มะม่วง",
    image: "/image/water/MangoLassi.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 5,
    protein: 0.1,
    carbs: 1.2,
    fat: 0,
    price: 59,
  },


  {
    id: 21,
    name: "อกไก่ย่าง",
    image: "/image/food/GrilledChicken.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    price: 89,
  },
  {
    id: 22,
    name: "สเต๊กปลาแซลมอน",
    image: "/image/food/SalmonSteak.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 206,
    protein: 22,
    carbs: 0,
    fat: 12,
    price: 159,
  },
  {
    id: 23,
    name: "แกงจืดเต้าหู้หมูสับใส่ผักกาดขาว",
    image: "/image/food/TofuSoup.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 120,
    protein: 10,
    carbs: 5,
    fat: 7,
    price: 69,
  },
  {
    id: 24,
    name: "สลัดผักเคล / ผักโขมใส่อกไก่",
    image: "/image/food/ChickenSalad.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 180,
    protein: 24,
    carbs: 8,
    fat: 5,
    price: 59,
  },
  {
    id: 25,
    name: "ไข่ต้ม (2 ฟอง)",
    image: "/image/food/BoiledEgg.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    price: 39,
  },
  {
    id: 26,
    name: "ยำทูน่าในน้ำแร่",
    image: "/image/food/TunaSalad.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 130,
    protein: 22,
    carbs: 6,
    fat: 1.5,
    price: 69,
  },
  {
    id: 27,
    name: "ต้มยำอกไก่น้ำใส",
    image: "/image/food/TomYumChicken.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 120,
    protein: 20,
    carbs: 4,
    fat: 2,
    price: 69,
  },
  {
    id: 28,
    name: "ข้าวกล้อง / ข้าวไรซ์เบอร์รี",
    image: "/image/food/Riceberry.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 1,
    price: 49,
  },
  {
    id: 29,
    name: "ผัดผักรวมมิตรกุ้ง",
    image: "/image/food/StirFriedVeg.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 110,
    protein: 3,
    carbs: 8,
    fat: 7,
    price: 69,
  },
  {
    id: 30,
    name: "กรีกโยเกิร์ต",
    image: "/image/food/Yogurt.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 180,
    protein: 9,
    carbs: 15,
    fat: 9,
    price: 59,
  },
];