import type { Food } from "./types";

// 3. ข้อมูลอาหารพร้อม Type
export const foods: Food[] = [
  {
    id: 1,
    name: "แอปเปิ้ล (ต่อ 1 ลูก)",
    image: "/image/fruit/Apple.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 72,
    protein: 0.4,
    carbs: 19.0,
    fat: 0.2,
    price: 39,
  },
  {
    id: 2,
    name: "อะโวคาโด (ต่อ 1 ลูก)",
    image: "/image/fruit/Avocado.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 240,
    protein: 3.0,
    carbs: 12.0,
    fat: 22.0,
    price: 49,
  },
  {
    id: 3,
    name: "กล้วยหอม (ต่อ 1 ลูก)",
    image: "/image/fruit/Banana.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.4,
    price: 29,
  },
  {
    id: 4,
    name: "บลูเบอร์รี (ต่อ 1 ถ้วยเล็ก)",
    image: "/image/fruit/Blueberry.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 84,
    protein: 1.1,
    carbs: 21.0,
    fat: 0.5,
    price: 49,
  },
  {
    id: 5,
    name: "ส้ม (ต่อ 1 ลูก)",
    image: "/image/fruit/Orange.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fat: 0.2,
    price: 39,
  },
  {
    id: 6,
    name: "ฝรั่ง (ต่อ 1 ลูก)",
    image: "/image/fruit/Guava.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 85,
    protein: 3.2,
    carbs: 18.0,
    fat: 1.2,
    price: 39,
  },
  {
    id: 7,
    name: "มะละกอสุก (ต่อ 1 จานจานเล็ก)",
    image: "/image/fruit/Papaya.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 65,
    protein: 0.8,
    carbs: 16.2,
    fat: 0.4,
    price: 29,
  },
  {
    id: 8,
    name: "แก้วมังกร (ต่อ 1 ลูก)",
    image: "/image/fruit/DragonFruit.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 72,
    protein: 1.5,
    carbs: 15.6,
    fat: 0.6,
    price: 39,
  },
  {
    id: 9,
    name: "แตงโม (ต่อ 1 จานชิ้นหั่น)",
    image: "/image/fruit/Watermelon.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 90,
    protein: 1.8,
    carbs: 22.8,
    fat: 0.6,
    price: 29,
  },
  {
    id: 10,
    name: "สตรอว์เบอร์รี (ต่อ 1 ถ้วยเล็ก)",
    image: "/image/fruit/Strawberry.jpg",
    category: "fruit",
    categoryName: "ผลไม้",
    calories: 50,
    protein: 1.0,
    carbs: 12.0,
    fat: 0.5,
    price: 49,
  },

  // --- หมวดเครื่องดื่ม (ต่อ 1 แก้ว) ---
  {
    id: 11,
    name: "ชาเขียวมะลิ (ต่อ 1 แก้ว)",
    image: "/image/water/JasmineGreenTea.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 5,
    protein: 0,
    carbs: 1.0,
    fat: 0,
    price: 39,
  },
  {
    id: 12,
    name: "ชาเขียวร้อน (ต่อ 1 แก้ว)",
    image: "/image/water/GreenTea.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 5,
    protein: 0,
    carbs: 1.0,
    fat: 0,
    price: 39,
  },
  {
    id: 13,
    name: "น้ำมะพร้าวสด (ต่อ 1 แก้ว)",
    image: "/image/water/CoconutWater.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 50,
    protein: 0.5,
    carbs: 12.0,
    fat: 0.2,
    price: 39,
  },
  {
    id: 14,
    name: "น้ำเต้าหู้ (ต่อ 1 แก้ว)",
    image: "/image/water/SoyMilk.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 140,
    protein: 8.0,
    carbs: 10.0,
    fat: 7.0,
    price: 29,
  },
  {
    id: 15,
    name: "น้ำขิง (ต่อ 1 แก้ว)",
    image: "/image/water/GingerTea.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 25,
    protein: 0.3,
    carbs: 6.0,
    fat: 0,
    price: 29,
  },
  {
    id: 16,
    name: "น้ำแครอทขิงแอปเปิลปั่น (ต่อ 1 แก้ว)",
    image: "/image/water/TomatoGingerApp.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 110,
    protein: 1.8,
    carbs: 26.0,
    fat: 0.5,
    price: 39,
  },
  {
    id: 17,
    name: "น้ำใบบัวบก (ต่อ 1 แก้ว)",
    image: "/image/water/GotuKolaJuice.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 90,
    protein: 0.6,
    carbs: 22.0,
    fat: 0.1,
    price: 29,
  },
  {
    id: 18,
    name: "นมอัลมอนด์ (ต่อ 1 แก้ว)",
    image: "/image/water/AlmondMilk.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 60,
    protein: 1.5,
    carbs: 2.0,
    fat: 5.0,
    price: 59,
  },
  {
    id: 19,
    name: "น้ำมะเขือเทศแตงกวาปั่น (ต่อ 1 แก้ว)",
    image: "/image/water/TomatoGourdSmoothie.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 65,
    protein: 1.8,
    carbs: 14.0,
    fat: 0.4,
    price: 39,
  },
  {
    id: 20,
    name: "ลาสซี่มะม่วง (ต่อ 1 แก้ว)",
    image: "/image/water/MangoLassi.jpg",
    category: "drink",
    categoryName: "เครื่องดื่ม",
    calories: 220,
    protein: 5.0,
    carbs: 38.0,
    fat: 4.5,
    price: 59,
  },

  // --- หมวดอาหาร (ต่อ 1 จาน / 1 ถ้วย) ---
  {
    id: 21,
    name: "อกไก่ย่าง (ต่อ 1 จาน)",
    image: "/image/food/GrilledChicken.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 250,
    protein: 45.0,
    carbs: 0,
    fat: 5.5,
    price: 89,
  },
  {
    id: 22,
    name: "สเต๊กปลาแซลมอน (ต่อ 1 จาน)",
    image: "/image/food/SalmonSteak.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 380,
    protein: 34.0,
    carbs: 0,
    fat: 22.0,
    price: 159,
  },
  {
    id: 23,
    name: "แกงจืดเต้าหู้หมูสับใส่ผักกาดขาว (ต่อ 1 ถ้วย)",
    image: "/image/food/TofuSoup.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 160,
    protein: 14.0,
    carbs: 8.0,
    fat: 8.0,
    price: 69,
  },
  {
    id: 24,
    name: "สลัดผักเคล / ผักโขมใส่อกไก่ (ต่อ 1 จาน)",
    image: "/image/food/ChickenSalad.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 280,
    protein: 32.0,
    carbs: 12.0,
    fat: 9.0,
    price: 59,
  },
  {
    id: 25,
    name: "ไข่ต้ม (ต่อ 2 ฟอง)",
    image: "/image/food/BoiledEgg.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 140,
    protein: 12.0,
    carbs: 1.0,
    fat: 10.0,
    price: 39,
  },
  {
    id: 26,
    name: "ยำทูน่าในน้ำแร่ (ต่อ 1 จาน)",
    image: "/image/food/TunaSalad.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 210,
    protein: 30.0,
    carbs: 8.0,
    fat: 2.5,
    price: 69,
  },
  {
    id: 27,
    name: "ต้มยำอกไก่น้ำใส (ต่อ 1 ถ้วย)",
    image: "/image/food/TomYumChicken.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 180,
    protein: 28.0,
    carbs: 6.0,
    fat: 3.5,
    price: 69,
  },
  {
    id: 28,
    name: "ข้าวกล้อง / ข้าวไรซ์เบอร์รี (ต่อ 1 จาน)",
    image: "/image/food/Riceberry.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 200,
    protein: 4.5,
    carbs: 44.0,
    fat: 1.6,
    price: 49,
  },
  {
    id: 29,
    name: "ผัดผักรวมมิตรกุ้ง (ต่อ 1 จาน)",
    image: "/image/food/StirFriedVeg.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 220,
    protein: 15.0,
    carbs: 14.0,
    fat: 11.0,
    price: 69,
  },
  {
    id: 30,
    name: "กรีกโยเกิร์ต (ต่อ 1 ถ้วย)",
    image: "/image/food/Yogurt.jpg",
    category: "food",
    categoryName: "อาหาร",
    calories: 180,
    protein: 15.0,
    carbs: 10.0,
    fat: 8.0,
    price: 59,
  },
];